#!/bin/sh
set -e

case "$1" in
    purge)
        # Purge deletes all persistent credentials and service configurations
        rm -rf /etc/endpoint-agent
        rm -f /etc/systemd/system/endpoint-agent.service
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
