#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop endpoint-agent.service || true
            systemctl disable endpoint-agent.service || true
        fi
        if [ -x /usr/bin/endpoint-agent ]; then
            /usr/bin/endpoint-agent -service uninstall || true
        fi
    ;;
    upgrade|failed-upgrade)
        if [ -d /run/systemd/system ]; then
            systemctl stop endpoint-agent.service || true
        fi
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
